# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/autoencoders-for-data-governance',
                'doc_host': 'https://oelmiedany.github.io',
                'git_url': 'https://github.com/oelmiedany/autoencoders-for-data-governance',
                'lib_path': 'autoencoders_for_data_governance'},
  'syms': { 'autoencoders_for_data_governance.core': { 'autoencoders_for_data_governance.core.foo': ( 'core.html#foo',
                                                                                                      'autoencoders_for_data_governance/core.py')}}}
